title: O. Lopatnov's Open Source Code
description: "I believe the best way to master a new technology is by building something meaningful. My goal is to create high-quality, free software that solves real problems. As a software developer, I invest my professional experience into personal projects and actively contribute to improving the tools I use. It’s rewarding to see my code making an impact. Open Source is my passion and my proof of expertise."
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
